githubConfigUrl: https://github.com/FortinetCloudCSE
githubConfigSecret: arc-github-app
runnerScaleSetName: org-runners
minRunners: 0
maxRunners: 30
runnerScaleSet:
  runners:
    labels:
      - org-runners
controllerServiceAccount:
  namespace: arc-systems
  name: gha-runner-scale-set-controller
containerMode:
  type: dind
template:
  spec:
    nodeSelector:
      node-role: runner
